service: pinpoint-playground

plugins:
  - serverless-pseudo-parameters # required for #{AWS::Region}:#{AWS::AccountId} syntax to work
  - serverless-webpack

package:
  individually: true

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: yarn

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  deploymentBucket: moonmail-v3-shared-deployments

  environment:
    DEBUG: true

functions:
  campaignHook:
    handler: src/campaignHook/handler.default

resources:
  Resources:
    PinpointLambdaPermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName:
          Ref: CampaignHookLambdaFunction
        Principal: pinpoint.#{AWS::Region}.amazonaws.com
        Action: lambda:InvokeFunction
        SourceArn: arn:aws:mobiletargeting:#{AWS::Region}:#{AWS::AccountId}:apps/*
        
